import sgMail from '@sendgrid/mail';

export const sendActivationMail = async (
    name: string,
    email: string,
    password: string,
    activationToken: string,
    autoGeneratedPassword: boolean
) => {
    const { SENDER_EMAIL, CLIENT_URL, SENDGRID_API_KEY } = process.env;

    if (!CLIENT_URL || !SENDGRID_API_KEY || !SENDER_EMAIL) {
        return false;
    }

    sgMail.setApiKey(SENDGRID_API_KEY);

    let passwordMsg: string;
    if (autoGeneratedPassword) {
        passwordMsg = `Jūsu parole ir <span style="color:red;">${password}</span>`;
        //passwordMsg = `Jūsu pagaidu parole ir <span style="color:red;">${password}</span>, vēlams to nomainīt`;
    } else {
        passwordMsg = `Izmantojiet paroli, ar kuru esat reģistrējušies`;
    }

    const msg = {
        to: email,
        from: SENDER_EMAIL,
        subject: 'Aktivizācija LU biznesa spēles kontam',
        text: 'Aktivizē savu LU biznesa spēles kontu',
        html: `
            <div style="max-width: 700px; text-align: center; font-size: 110%; font-family: Arial, Helvetica, sans-serif; margin:auto;">
                <div style="color: #ffffff; text-align: center; width: 100%; padding: 50px 20px; background-color: #021535;">
                <h2 style="color: #ffffff;">${name}</h2>
                
                <p style="color: #ffffff;"></p>
                
                <a clicktracking=off href="${CLIENT_URL}/activate/${activationToken}" style="background: crimson; text-decoration: none; color: white; padding: 10px 20px; margin: 10px 0; display: inline-block;">ACTIVATE ACCOUNT</a>
                <br />
                <strong style="text-align: center;">${passwordMsg}</strong>
                </div>
                <br />
            
                <small></small>
            </div>
        `,
    };

    const sendRes = await sgMail.send(msg);

    const statusCode = sendRes[0].statusCode;

    if (statusCode !== 202) {
        return false;
    }

    return true;
};

export const sendResetPasswordEmail = async (
    name: string,
    email: string,
    resetPasswordToken: string
) => {
    const { SENDER_EMAIL, CLIENT_URL, SENDGRID_API_KEY } = process.env;

    if (!CLIENT_URL || !SENDGRID_API_KEY || !SENDER_EMAIL) {
        return false;
    }

    sgMail.setApiKey(SENDGRID_API_KEY);

    const msg = {
        to: email,
        from: SENDER_EMAIL,
        subject: 'LU biznesa spēles konta paroles atjaunošana',
        text: 'Saņemts pieprasījums Jūsu LU biznesa spēles konta paroles atjaunošanai',
        html: `
        <div style="max-width: 700px; text-align: center; font-size: 110%; font-family: Arial, Helvetica, sans-serif; margin:auto;">
            <div style="color: #ffffff; text-align: center; width: 100%; padding: 50px 20px; background-color: #021535;">
            <h2 style="color: #ffffff;">${name}</h2>
            
            <p style="color: #ffffff;"></p>
            
            <strong style="text-align: center;">Mēs esam saņēmuši pieprasījumu Jūsu paroles atjaunošanai.</strong>
            <br />
        
            <a clicktracking=off href="${CLIENT_URL}/reset-password/${resetPasswordToken}" style="background: crimson; text-decoration: none; color: white; padding: 10px 20px; margin: 10px 0; display: inline-block;">RESET PASSWORD</a>
            
            <br /><br>
            <strong style="text-align: center;">Gadijumā, ja tas nebijāt Jūs, <span style="color: red;">ignorējiet šo e-pastu.</span></strong>
            </div>
            <br />
        
            <small></small>
        </div>
        `,
    };

    const sendRes = await sgMail.send(msg);

    const statusCode = sendRes[0].statusCode;

    if (statusCode !== 202) {
        return false;
    }

    return true;
};
